# Generated by Django 3.1.7 on 2021-03-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(max_length=1024, verbose_name='Содержание статьи')),
                ('image', models.FileField(blank=True, null=True, upload_to='blog_posts/')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('in_archive', models.BooleanField(default=False, verbose_name='В архиве')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.blogcategory', verbose_name='Имя категории')),
            ],
        ),
    ]
